name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: cd backend && yarn install

      - name: Build
        run: cd backend && yarn build
        env:
          SKIP_ENV_VALIDATION: true

  frontend:
    name: Frontend Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build
        run: cd frontend && npm run build
